spring:
  application.name: spring-profiles-example
  profiles.active: local
---
spring:
  profiles: local

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: erm_user
    password: erm
  jpa:
    database: oracle
    show-sql: true
    hibernate.ddl-auto: update
---
spring:
  profiles: dev

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@ora-ts11.sjk.emb:1521:ts11
    username: erm_user
    password: erm
  jpa:
    database: oracle
    show-sql: true
    hibernate.hbm2ddl.auto: update
---
spring:
  profiles: integration-test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:integration-test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    database: h2
    show-sql: true
    hibernate.hbm2ddl.auto: update
---
spring:
  profiles: prod

  datasource:
  jndi-name: java:jboss/datasources/pocDS
  jpa:
    database: oracle
    show-sql: false